name: YouTubeClone-CICD

trigger:
- main

stages:
  - stage: Build
    jobs:
      - job: Build
        pool: 
         vmImage: 'ubuntu-latest'
        steps: 
         - task: Npm@1
           inputs:
             command: install
         - task: Npm@1
           inputs:
            command: custom
            customCommand: 'run build'
         - task: PublishBuildArtifacts@1
           inputs:
             PathtoPublish: 'build'
             ArtifactName: 'drop'
             publishLocation: Container

  - stage: Deployment
    jobs:
      - job: Deployment
        pool:
         vmImage: 'ubuntu-latest'
        steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              downloadType: single
              buildType: current
              downloadPath: '$(System.ArtifactStagingDirectory)'
              artifactName: 'drop'

          - task: AzureRmWebAppDeployment@4
            inputs:
             ConnectionType: 'AzureRM'
             azureSubscription: 'AzureWebApps'
             appType: 'webAppLinux'
             WebAppName: 'YoutubeClone2'
             packageForLinux: '$(System.ArtifactStagingDirectory)/drop'
             RuntimeStack: 'NODE|20-lts'
             #DeploymentTypeLinux: 'oneDeploy'
